# Generated by Django 5.2.12 on 2026-03-06 21:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('mac_address', models.CharField(default='Unknown', max_length=17)),
                ('role', models.CharField(default='Client Device', max_length=50)),
                ('device_type', models.CharField(default='PC', max_length=50)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('ports', models.JSONField(default=list)),
            ],
        ),
    ]
