# Generated by Django 5.2.12 on 2026-03-27 19:43

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0003_loginactivity_update_device_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_ip_range', models.CharField(default='192.168.1.0/24', help_text='Default CIDR subnet used when the dashboard loads.', max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid CIDR subnet (e.g. 192.168.1.0/24).', regex='^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}/\\d{1,2}$')])),
                ('scan_interval', models.CharField(choices=[('30', '30 Seconds'), ('60', '1 Minute'), ('300', '5 Minutes'), ('600', '10 Minutes')], default='60', help_text='How often the dashboard auto-scans (seconds).', max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.CreateModel(
            name='ITContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('CISO', 'CISO'), ('IT_MGMT', 'IT Management'), ('STAFF', 'Staff Member'), ('SOC', 'SOC Analyst'), ('NETADMIN', 'Network Admin'), ('SYSADMIN', 'System Admin'), ('HELPDESK', 'Help Desk')], default='STAFF', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–20 digits, spaces, dashes allowed).', regex='^\\+?[\\d\\s\\-\\(\\)]{7,20}$')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
    ]
