# Generated by Django 5.2.12 on 2026-05-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0004_globalsettings_itcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='level_1_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='level_2_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='level_3_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
