# Generated by Django 5.2.12 on 2026-05-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0005_globalsettings_level_1_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginactivity',
            name='event',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('FAILED', 'Failed Login'), ('SCAN', 'Network Scan'), ('ESCALATE', 'Escalation')], max_length=10),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
