# Generated by Django 5.2.15 on 2026-06-13 20:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0006_alter_loginactivity_event_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=150, unique=True)),
                ('asset_type', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('owner_name', models.CharField(max_length=120)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_contact', models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–20 digits, spaces, dashes allowed).', regex='^\\+?[\\d\\s\\-\\(\\)]{7,20}$')])),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=120)),
                ('business_unit', models.CharField(max_length=100)),
                ('criticality', models.CharField(choices=[('Critical', 'Critical 🔴'), ('High', 'High 🟠'), ('Medium', 'Medium 🟡'), ('Low', 'Low 🟢')], default='Low', max_length=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, default='', max_length=17)),
                ('operating_system', models.CharField(blank=True, default='', max_length=100)),
                ('vendor', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Under Maintenance'), ('Decommissioned', 'Decommissioned')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset_name'], name='network_app_asset_n_ab0988_idx'), models.Index(fields=['ip_address'], name='network_app_ip_addr_d2f496_idx'), models.Index(fields=['criticality'], name='network_app_critica_38630a_idx')],
            },
        ),
    ]
