# Generated by Django 6.0.5 on 2026-07-17 09:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0010_vulnerability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assignment_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='incident',
            name='commands_executed',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='configuration_changes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='patch_applied',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='remediation_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='verification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('Successful', 'Successful'), ('Failed', 'Failed'), ('Needs Rework', 'Needs Rework')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='version_after',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='version_before',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Active', 'Active'), ('Acknowledged', 'Acknowledged'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Reopened', 'Reopened')], default='New', max_length=20),
        ),
        migrations.CreateModel(
            name='IncidentComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='network_app.incident')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'IncidentComments',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IncidentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidences/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='network_app.incident')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'IncidentEvidence',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
