# Generated by Django 6.0.5 on 2026-07-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0011_remediation_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='alert',
            field=models.CharField(default='OK', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='firewall',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='hostname',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='inactive',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='os',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='rogue',
            field=models.CharField(default='Normal', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='vendor',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
