# Generated by Django 6.0.5 on 2026-07-17 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0012_device_alert_device_firewall_device_hostname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('network_subnet', models.CharField(blank=True, default='', max_length=100)),
                ('devices', models.ManyToManyField(related_name='scan_sessions', to='network_app.device')),
            ],
        ),
    ]
