# Generated by Django 6.0.5 on 2026-07-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0013_alter_device_ip_address_scansession'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='Notification', max_length=50),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Active', 'Active'), ('Acknowledged', 'Acknowledged'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Archived', 'Archived'), ('Suppressed', 'Suppressed')], default='Active', max_length=20),
        ),
    ]
